# Copyright (c) 2024 StackHPC Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

import json
import logging
from typing import List

LOG = logging.getLogger(__name__)


class Stats(object):
    """Kayobe Ansible statistics.

    This class represents the statistics generated by the openstack.kolla.stats
    callback plugin, and needs to be kept in sync with it.
    """

    num_failures: int
    num_unreachable: int
    failures: List[str]
    unreachable: List[str]
    no_hosts_remaining: bool

    def __init__(self, num_failures=0, num_unreachable=0, failures=None,
                 unreachable=None, no_hosts_remaining=False, **kwargs):
        if kwargs:
            LOG.warning(f"Unexpected Ansible stats returned by "
                        "openstack.kolla.stats callback plugin: "
                        "{kwargs.keys()}")
        self.num_failures = num_failures
        self.num_unreachable = num_unreachable
        self.failures = failures or []
        self.unreachable = unreachable or []
        self.no_hosts_remaining = no_hosts_remaining

    @classmethod
    def from_json(cls, json_path: str):
        """Construct a Stats object from statistics in a JSON file."""
        try:
            with open(json_path) as f:
                return cls(**json.load(f))
        except (FileNotFoundError, PermissionError) as exc:
            # This could be caused by:
            # - incorrect config preventing the callback plugin from loading
            # - an early failure in Ansible preventing the v2_on_stats callback
            #   from executing
            # - failure to create the stats file
            # - something else
            LOG.error(f"Unable to open Ansible stats JSON file: {exc}")
            LOG.error(f"Is the openstack.kolla.stats plugin included in the "
                      "[defaults] callbacks_enabled list in ansible.cfg?")
            return None

    def completed_without_failures(self) -> bool:
        """Return whether execution continued to completion without failures.

        Unreachable hosts are not counted as failures in this context.
        """
        return self.num_failures == 0 and not self.no_hosts_remaining
